services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "3001:3000"
    volumes: 
      - ./app/database.db:/app/app/database.db
      - ./app/chats:/app/app/chats
      - ./app/photos:/app/app/photos

  nginx:
    image: nginx:1.24.0
    ports:
      - "81:81"
      - "8443:8443"
    volumes:
      - ./default-dev.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - nodejs

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
