services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"
    volumes: 
      - /data/servisplus_demo/database.db:/app/app/database.db
      - /data/servisplus_demo/chats:/app/app/chats
      - /data/servisplus_demo/photos:/app/app/photos

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default-demo.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - nodejs

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
