services:
  nodejs:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.nodejs
    ports:
      - "3000:3000"
    volumes: 
      - /data/servisplus_prod/database.db:/app/app/database.db
      - /data/servisplus_prod/chats:/app/app/chats
      - /data/servisplus_prod/photos:/app/app/photos

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../configs/default-prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - nodejs

  bot:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.bot
    restart: always
