networks:
  dev_network:
services:
  nodejs:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.nodejs
    ports:
      - "3001:3000"
    volumes: 
      - /data/servisplus_dev/database.db:/app/app/database.db
      - /data/servisplus_dev/chats:/app/app/chats
      - /data/servisplus_dev/photos:/app/app/photos
    networks:
      - dev_network
    container_name: dev_nodejs

  nginx:
    image: nginx:1.24.0
    ports:
      - "81:80"
      - "8443:443"
    volumes:
      - ../configs/default-dev.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - nodejs
    networks:
      - dev_network
    container_name: dev_nginx

  bot:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.bot
    restart: always
    networks:
      - dev_network
    container_name: dev_bot
