networks:
  demo_network:
services:
  nodejs:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.nodejs
    ports:
      - "3002:3000"
    volumes: 
      - /data/servisplus_demo/database.db:/app/app/database.db
      - /data/servisplus_demo/chats:/app/app/chats
      - /data/servisplus_demo/photos:/app/app/photos
    networks:
      - demo_network

  nginx:
    image: nginx:1.24.0
    ports:
      - "82:80"
      - "9443:443"
    volumes:
      - ../configs/default-demo.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - nodejs
    networks:
      - demo_network

  bot:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.bot
    restart: always
    networks:
      - demo_network
